version: '3.8'

networks:
  aerocode:
    name: aerocode

services:
  mysql:
    image: mysql:8.0
    container_name: aerocode_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aerocode
      MYSQL_DATABASE: aerocode
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - aerocode
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-paerocode"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: ./back
    container_name: aerocode_app
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:aerocode@mysql:3306/aerocode
      JWT_SECRET: aerocode_secret_key_muito_segura
    ports:
      - "3000:3000"
    networks:
      - aerocode
    depends_on:
      mysql:
        condition: service_healthy

  front:
    build: ./front
    container_name: aerocode_front
    restart: always
    environment:
      VITE_API_TARGET: http://app:3000
    ports:
      - "5173:5173"
    networks:
      - aerocode
    depends_on:
      - app

volumes:
  mysql_data:
